In [ ]:
# NOTE: "made code on github only available for Colab usage, will remove it afterwards again"

## commands for training models and generating saved models (for analysing step)
Appendix:

"For p(z) = N (z; 0, diag(σ)), experiments were run with 

a batch size of 64 and for 20 epochs. For p(z) = 􏰐d STUDENT-T(zd; ν), 

experiments were run with a batch size of 256 and for 40 epochs"

### T-Student's with different degrees of freedom
```
# here batch size and nb epochs different; choose anyway 20, otherwise too much time
DF=2; python main.py --cuda-dev=4 --name dsprites_beta_1_pz_st_$DF --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 256 --latent-dim 10 --beta 1. --prior StudentT --df $DF
DF=5; python main.py --cuda-dev=4 --name dsprites_beta_1_pz_st_$DF --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 256 --latent-dim 10 --beta 1. --prior StudentT --df $DF
DF=9; python main.py --cuda-dev=2 --name dsprites_beta_1_pz_st_$DF --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 256 --latent-dim 10 --beta 1. --prior StudentT --df $DF
DF=12; python main.py --cuda-dev=2 --name dsprites_beta_1_pz_st_$DF --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 256 --latent-dim 10 --beta 1. --prior StudentT --df $DF
DF=9999; python main.py --cuda-dev=6 --name dsprites_beta_1_pz_st_$DF --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 256 --latent-dim 10 --beta 1. --prior StudentT --df $DF

```

### Isotropic gaussian or anistropic gaussian with learned or fixed PCA

```

BETA=1 python main.py --cuda-dev=8 --name dsprites_beta_$BETA\_pz_norm_iso --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance iso
BETA=1 python main.py --cuda-dev=8 --name dsprites_beta_$BETA\_pz_norm_pca --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance pca
BETA=1 python main.py --cuda-dev=8 --name dsprites_beta_$BETA\_pz_norm_pca_learn --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance pca \
    --learn-prior-variance

# --- done

BETA=2; python main.py --cuda-dev=6 --name dsprites_beta_$BETA\_pz_norm_iso --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance iso
BETA=2; python main.py --cuda-dev=7 --name dsprites_beta_$BETA\_pz_norm_pca --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance pca
BETA=2; python main.py --cuda-dev=8 --name dsprites_beta_$BETA\_pz_norm_pca_learn --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance pca \
    --learn-prior-variance

# --- done

BETA=4; python main.py --cuda-dev=9 --name dsprites_beta_$BETA\_pz_norm_iso --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance iso
BETA=4; python main.py --cuda-dev=6 --name dsprites_beta_$BETA\_pz_norm_pca --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance pca
BETA=4; python main.py --cuda-dev=7 --name dsprites_beta_$BETA\_pz_norm_pca_learn --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance pca \
    --learn-prior-variance

# --- done

BETA=8; python main.py --cuda-dev=7 --name dsprites_beta_$BETA\_pz_norm_iso --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance iso
BETA=8; python main.py --cuda-dev=8 --name dsprites_beta_$BETA\_pz_norm_pca --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance pca
BETA=8; python main.py --cuda-dev=6 --name dsprites_beta_$BETA\_pz_norm_pca_learn --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance pca \
    --learn-prior-variance

# --- done

BETA=16; python main.py --cuda-dev=8 --name dsprites_beta_$BETA\_pz_norm_iso --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance iso
BETA=16; python main.py --cuda-dev=8 --name dsprites_beta_$BETA\_pz_norm_pca --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance pca
BETA=16; python main.py --cuda-dev=6 --name dsprites_beta_$BETA\_pz_norm_pca_learn --model dsprites \
    --skip-test --epochs 20 --lr 1e-4 --batch-size 64 --latent-dim 10 --beta $BETA --prior-variance pca \
    --learn-prior-variance
```

In [4]:
import os
os.chdir('src')
import analyse

In [5]:
path_experiments = '../experiments'

In [11]:
# calculate disentanglement for each experiment
for exp_name in os.listdir(path_experiments):
    print(exp_name)
    sub_dirs = os.listdir('{}/{}'.format(path_experiments, exp_name))
    # for each experiment, made only one run
    assert len(sub_dirs) == 1
    sub_dir = sub_dirs[0]
    path = os.path.join(path_experiments, exp_name, sub_dir)
    result = analyse.run(
        path,
        disentanglement=True
    )

dsprites_beta_2_pz_norm_pca
p(z):
<class 'torch.distributions.normal.Normal'>
(tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), tensor([[0.6882, 0.7913, 0.7979, 0.9221, 0.9242, 0.9248, 0.9362, 1.2132, 1.2307,
         1.3569]]))
q(z|x):
<class 'torch.distributions.normal.Normal'>
Load training data...
Load testing data...
Loss: 74.4 Recon: -36.8 KL: 18.8 Reg: 0.000
Disentanglement: 0.631 (wo OT 0.629)
dsprites_beta_4_pz_norm_pca
p(z):
<class 'torch.distributions.normal.Normal'>
(tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), tensor([[0.6882, 0.7913, 0.7979, 0.9221, 0.9242, 0.9248, 0.9362, 1.2132, 1.2307,
         1.3569]]))
q(z|x):
<class 'torch.distributions.normal.Normal'>
Load training data...
Load testing data...
Loss: 108.7 Recon: -54.4 KL: 13.6 Reg: 0.000
Disentanglement: 0.714 (wo OT 0.714)
dsprites_beta_4_pz_norm_pca_learn
p(z):
<class 'torch.distributions.normal.Normal'>
(tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), tensor([[0.6882, 0.7913, 0.7979, 0.9221, 0.924

In [12]:
result

defaultdict(list,
            {'test_loss': [51.283004479938086],
             'test_recon': [-23.542267998887432],
             'test_kl': [27.74073648750782],
             'test_reg': [0.0],
             'test_disentanglement': [0.7054499983787537],
             'test_disentanglement2': [0.7072499990463257]})

In [14]:
import torch

In [15]:
results = {}
# calculate disentanglement for each experiment
for exp_name in os.listdir(path_experiments):
    print(exp_name)
    sub_dir = os.listdir('{}/{}'.format(path_experiments, exp_name))[0]
    path = os.path.join(path_experiments, exp_name, sub_dir)
    path_result = os.path.join(path, )
#     results[exp_name] = torch.load()

dsprites_beta_2_pz_norm_pca
dsprites_beta_4_pz_norm_pca
dsprites_beta_4_pz_norm_pca_learn
dsprites_beta_1_pz_st_2
dsprites_beta_16_pz_norm_pca
dsprites_beta_1_pz_st_9999
dsprites_beta_1_pz_norm_pca
dsprites_beta_8_pz_norm_pca
dsprites_beta_2_pz_norm_iso
dsprites_beta_1_pz_st_5
dsprites_beta_2_pz_norm_pca_learn
dsprites_beta_16_pz_norm_pca_learn
dsprites_beta_1_pz_norm_pca_learn
dsprites_beta_4_pz_norm_iso
dsprites_beta_1_pz_st_12
dsprites_beta_8_pz_norm_pca_learn
dsprites_beta_1_pz_st_9
dsprites_beta_16_pz_norm_iso
dsprites_beta_8_pz_norm_iso
dsprites_beta_1_pz_norm_iso


In [ ]:
import torch

In [ ]:
z = torch.load(
    '/export/home/vtschern/workspace/test/experiments/2020-03-30T01_28_17.273538zqphwnru/losses.rar'
)